name: Build and test
on:
  workflow-call:
    inputs:
      upload-pages-artifact:
        type: boolean
        required: false
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
# steps template: - [keyword]: [action]
      - uses: actions/checkout@v4 # navigates to the active branch directory
      - uses: actions/setup-node@v4 # self defining
        with:
          node-version: 21
      - run: npm ci
      - run: npm run build
      - run: npm run test:integration
      - run: npm run test:e2e
      - uses: actions/upload-artifact@v3
        with:
          name: e2e-videos
          path: cypress/videos/
      - if: ${{ inputs.upload-pages-artifact }}
        uses: actions/upload-pages-artifact@v1
          with:
            path: build/
